### ISSUE TITLE
API Key Should Not be Hardcoded

### ISSUE THREAD

**Issue by thomastu** [davidrpugh/pyBEA#3]
In line 22 of ```pyBEA/pybea/api.py```, you have hardcoded your api_key.  

Another way to go about this is to feed in a key in the __init__, or have some kind of config file that gets added to your .gitignore and documented on the README.

**Comment by davidrpugh** [comment]
@thomastu 

Thanks for the heads up.  I thought that the API key was for the pyBEA project and thus the user shouldn't need to provide their own.  If this is not the case, then the easiest way would be to add the api key as a keyword argument to the `__init__`.

**Comment by davidrpugh** [comment]
@thomastu I have released an updated version of pyBEA that no longer hard codes the BEA API key as you have suggested.
